fail_fast: true
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
